import sqlite3
def table(DATE,TIME,REMOTE_IP,REMOTE_PORT,DIRECTION,LOCAL_IP,LOCAL_PORT,PROTOCOL,BYTES,COUNTRY,PACKET_DETAIL):
	conn = sqlite3.connect('test.db')
	tb_create = ''' CREATE TABLE IF NOT EXISTS HONEYPOT
	(DATE TEXT NOT NULL,
	TIME TEXT NOT NULL,
	REMOTE_IP TEXT NOT NULL,
	REMOTE_PORT TEXT NOT NULL,
	DIRECTION TEXT NOT NULL,
	LOCAL_IP TEXT NOT NULL,
	LOCAL_PORT TEXT NOT NULL,
	PROTOCOL TEXT NOT NULL,
	BYTES TEXT NOT NULL,
	COUNTRY TEXT NOT NULL,
	PACKET_DETAIL BLOB  NULL);'''
	tb_insert= "INSERT INTO HONEYPOT(DATE,TIME,REMOTE_IP,REMOTE_PORT,DIRECTION,LOCAL_IP,LOCAL_PORT,PROTOCOL,BYTES,COUNTRY,PACKET_DETAIL) VALUES(?,?,?,?,?,?,?,?,?,?,?);"

	tb_exists = "SELECT DATE,TIME,REMOTE_IP,REMOTE_PORT,DIRECTION,LOCAL_IP,LOCAL_PORT,PROTOCOL,BYTES,COUNTRY,PACKET_DETAIL FROM HONEYPOT"
        try:
	    conn.execute(tb_create)
	    conn.execute(tb_insert,(DATE,TIME,REMOTE_IP,REMOTE_PORT,DIRECTION,LOCAL_IP,LOCAL_PORT,PROTOCOL,BYTES,COUNTRY,PACKET_DETAIL))
	    conn.commit()
	except Exception, e:
            print e

		
